spring:
  profiles:
  active: local
---
spring:
  profiles:local
  kafka:
    producer:
      bootstrap-servers:  localhost:9093,localhost:9094,localhost:9095
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

      spring:
        profiles: dev
        kafka:
          producer:
            bootstrap-servers: dev:9093
            key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

            spring:
              profiles: prod
              kafka:
                producer:
                  bootstrap-servers: prod:9093
                  key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
                  value-serializer: org.apache.kafka.common.serialization.StringSerializer